import Head from "next/head";
import "../styles/globals.css";
import { CursorProvider } from "react-cursor-custom";
import { useEffect } from "react";

function MyApp({ Component, pageProps }) {
  var cursor;
  var cursor2;

  useEffect(() => {
    cursor = document.getElementById("cursor");
    document.body.addEventListener("mousemove", function (e) {
      (cursor.style.left = e.clientX + "px"),
        (cursor.style.top = e.clientY + "px");
    });

    cursor2 = document.getElementById("cursor2");
    document.body.addEventListener("mousemove", function (e) {
      (cursor2.style.left = e.clientX + "px"),
        (cursor2.style.top = e.clientY + "px");
    });
  }, []);

  return (
    <>
      <Head>
        <title>Treasure Hunt</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div class="cursor2" id="cursor2"></div>
      <div class="cursor" id="cursor"></div>

      {/* <CursorProvider transitionTime={100}> */}
      <Component {...pageProps} />
      {/* </CursorProvider> */}
    </>
  );
}

export default MyApp;
